package aoc_2025_day07

import aoc_helpers "github.com/Djosar/advent-of-code/util/aoc-helpers"

const testInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func Day07() *aoc_helpers.AOCDay {
	day := aoc_helpers.NewDay(7, 2025, testInput)
	day.PushTask(part01)
	day.PushTask(part02)
	return day
}

func part01(d *aoc_helpers.AOCDay) (any, error) {

	return 0, nil
}

func part02(d *aoc_helpers.AOCDay) (any, error) {
	return 0, nil
}
